### PR TITLE
cargo: Bump prost version

### LINKED ISSUE #260: Failed to build with latest tonic v0.8.0
```
   Compiling tonic v0.8.0
error[E0277]: the trait bound `utils::keyprovider::KeyProviderKeyWrapProtocolInput: prost::message::Message` is not satisfied
   --> src/utils/keyprovider.rs:100:60
    |
100 |             self.inner.unary(request.into_request(), path, codec).await
    |                        -----                               ^^^^^ the trait `prost::message::Message` is not implemented for `utils::keyprovider::KeyProviderKeyWrapProtocolInput`
    |                        |
    |                        required by a bound introduced by this call
    |
    = note: required because of the requirements on the impl of `Codec` for `ProstCodec<utils::keyprovider::KeyProviderKeyWrapProtocolInput, _>`
note: required by a bound in `tonic::client::Grpc::<T>::unary`
   --> /home/arron/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.0/src/client/grpc.rs:149:12
    |
149 |         C: Codec<Encode = M1, Decode = M2>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `tonic::client::Grpc::<T>::unary`

error[E0277]: the trait bound `utils::keyprovider::KeyProviderKeyWrapProtocolOutput: prost::message::Message` is not satisfied

```
The build with works with:
```
tonic = { version = "0.7.2", optional = true }
```
@pravinrajr9 Could you help to fix this issue?

### PR DESCRIPTION
**Pull request by stevenhorsman**
Now ocicryprt-rs is picking up 0.8.0 of tonic, it needs to use 0.11.0
of post

Whether we want to have `>=` versions of dependencies and risk them getting
out of sync - I'm not sure, but hopefully
this fixes the build problems in the short term

Fixes: confidential-containers/guest-components#260
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Review by pravinrajr9 — APPROVED** [review]

**Comment by stevenhorsman** [comment]
Hey @pravinrajr9 (thanks for the review) & @arronwy - I saw there was a problem in the CI workflow due to protoc not being pulled in, so I fixed that, but now we are hitting some clippy failures in beta and nightly. I've fixed one of them, but I'm not sure of the fix for the zero-size vector and the other two and in generated code. If you can take a look and advise that would be great. I think that the problems weren't introduced by this PR, so if we need to wait for tonic to fix the clippy problems I wonder if we could merge this anyway to unblock the issues with building image-rs?

**Review by arronwy — APPROVED** [review]
Thanks @stevenhorsman , the clippy error is auto generated code, we can merge this pr to avoid block our build.
